@host=http://localhost:{{$dotenv SERVER_PORT}}
### Healthcheck 
GET {{host}}/health
### static NeTEx parking data
GET {{host}}/netex/parking
### static NeTEx mobility sharing data
GET {{host}}/netex/sharing
### SIRI-FM real time parking availability. Station ID as a parameter
GET {{host}}/siri/fm/115

### parking
GET https://mobility.api.opendatahub.com/v2/flat/ParkingStation
?where=sactive.eq.true,sorigin.in.(FBK,A22,Municipality Merano,FAMAS)
### Bike sharing bolzano sharing service
GET https://mobility.api.opendatahub.testingmachine.eu/v2/flat/BikesharingStation
?where=sorigin.eq.BIKE_SHARING_BOLZANO,sactive.eq.true
### Bike sharing bolzano single bicycles
GET https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Bicycle
?where=sorigin.eq.BIKE_SHARING_BOLZANO,sactive.eq.true
&limit=-1
### Bike boxes parking
GET https://mobility.api.opendatahub.testingmachine.eu/v2/flat/BikeParking
?where=sorigin.eq.bicincitta,sactive.eq.true
&limit=-1
### Bike sharing merano
GET https://mobility.api.opendatahub.com/v2/flat/Bicycle
?where=sorigin.eq.BIKE_SHARING_MERANO,sactive.eq.true
### Bike sharing PAPIN
GET https://mobility.api.opendatahub.com/v2/flat/BikesharingStation
?where=sorigin.eq.BIKE_SHARING_PAPIN,sactive.eq.true
### Car sharing HAL
GET https://mobility.api.opendatahub.com/v2/flat/CarsharingStation
?where=sorigin.eq.HAL-API,sactive.eq.true
### Car sharing HAL single cars
GET https://mobility.api.opendatahub.com/v2/flat/CarsharingCar
?where=sorigin.eq.HAL-API,sactive.eq.true
### parking station Echarging
GET https://mobility.api.opendatahub.com/v2/flat/EChargingStation
?where=sactive.eq.true,scoordinate.bbi.(10.368347,46.185535,12.551880,47.088826,4326)
### parking station realtime
GET https://mobility.api.opendatahub.com/v2/flat/ParkingStation,BikeParking,EChargingStation/free,number-available/latest
?where=sactive.eq.true,sorigin.in.(FBK,A22,Municipality Merano,FAMAS,bicincitta,ALPERIA,route220,DRIWE)
&select=mperiod,mvalue,mvalidtime,scode,stype,smetadata.capacity,smetadata.totalPlaces

### Bikesharing station realtime (station based)
GET https://mobility.api.opendatahub.com/v2/flat/BikesharingStation/number-available,free-bays/latest
?where=sorigin.eq.BIKE_SHARING_BOLZANO,sactive.eq.true
&select=mperiod,mvalue,mvalidtime,scode,sname,tname

### Bikesharing station realtime (free floating)
GET https://mobility.api.opendatahub.com/v2/flat/Bicycle/availability/latest
?where=sorigin.eq.BIKE_SHARING_MERANO,sactive.eq.true
&select=mperiod,mvalue,mvalidtime,scode,sname,scoordinate

### Carsharing station realtime
GET https://mobility.api.opendatahub.com/v2/flat/CarsharingStation/number-available/latest
?where=sorigin.eq.HAL-API,sactive.eq.true

###
GET https://mobility.api.opendatahub.com/v2/flat/BikesharingStation/availability,free-bays/latest
?where=scode.eq."BIKE_SHARING_PAPIN:58"
#&select=tname,mperiod,mvalue,mvalidtime,scode